---
# Copyright 2016, AT&T, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
## Deployment Options:
bootstrap_os: ubuntu
public_iface: enp0s3
nat_iface: enp0s3
proxy_enable: false
#
#
## Kubernetes Parameters:
kubectl_endpoint: kube1
kubelet_hostname_override: true
init_token: ac7da3.b2cofcda6ab01976
kube_version: v1.5.4
#
#
## Kubernetes SDN Deployment Options:
kube_cluster_ip_cidr: 10.96.0.0/12
kube_service_dns_domain: cluster.local
kube_sdn_deploy: true
kube_sdn: weave

#
## Kubernetes SDN Versioning:
calico_version: v2.0
romana_version: v0.9.3.6
#
#
## Kubernetes Add-Ons:
# Optional Items: kube_dashboard, kube_helm (more to come).
kube_addons_enabled: true
kube_addons:
  - kube_dashboard
  - kube_helm
#
## Helm Parameters:
helm_version: v2.1.0
#
## Docker Daemon Options:
# Shared mounts is required for several OpenStack Kolla-Kubernetes components.
docker_shared_mounts: false
#
## Registry Type:
# Possible values: default, docker_insecure
registry_type: default
# For use with registry_type of docker_insecure
docker_insecure_registry: 10.0.2.2:5000
#
## Kolla-Kubernetes addtional options:
# Setup the host to use the kube-dns nameservers (required for ceph)
setup_host_kube_dns: false
# Setup the host for ceph
setup_host_ceph: false
# Patch kubernetes-controller-manager for ceph PVC support
# This pulls in quay.io/attcomdev/kube-controller-manager:v1.5.4
# to replace the upstream image
patch_kube_ceph: false
